"""add_plan_code_to_applications_and_individual_entrepreneurs

Revision ID: 1bc23f385037
Revises: 126b7182912f
Create Date: 2025-11-12 13:56:08.518033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bc23f385037'
down_revision: Union[str, None] = '126b7182912f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individual_entrepreneurs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('bin', sa.String(length=20), nullable=True),
    sa.Column('plan_code', sa.String(length=50), nullable=False),
    sa.Column('factory_limit', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ip_factory_association',
    sa.Column('ip_id', sa.UUID(), nullable=False),
    sa.Column('factory_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.ForeignKeyConstraint(['ip_id'], ['individual_entrepreneurs.id'], ),
    sa.PrimaryKeyConstraint('ip_id', 'factory_id')
    )
    op.add_column('applications', sa.Column('plan_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'plan_code')
    op.drop_table('ip_factory_association')
    op.drop_table('individual_entrepreneurs')
    # ### end Alembic commands ###

