"""Initial migration

Revision ID: fe5c8821a71f
Revises: 
Create Date: 2025-11-10 21:38:53.182120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe5c8821a71f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_ru', sa.String(length=200), nullable=False),
    sa.Column('name_kk', sa.String(length=200), nullable=True),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('kpi_calculations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('period_type', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('oee_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('availability', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('performance', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('quality', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_production', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('planned_production', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('production_variance', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('downtime_minutes', sa.Integer(), nullable=True),
    sa.Column('downtime_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('unplanned_downtime_minutes', sa.Integer(), nullable=True),
    sa.Column('energy_consumption_kwh', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('energy_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('specific_energy', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('defect_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rework_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('costs', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('profit_margin', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metrics_catalog',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_ru', sa.String(length=200), nullable=False),
    sa.Column('name_kk', sa.String(length=200), nullable=True),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('min_value', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('optimal_min', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('optimal_max', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('critical_min', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('critical_max', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=True),
    sa.Column('applicable_to', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=True),
    sa.Column('is_kpi', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('equipment_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_ru', sa.String(length=200), nullable=False),
    sa.Column('name_kk', sa.String(length=200), nullable=True),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('industry_id', sa.UUID(), nullable=True),
    sa.Column('default_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('maintenance_interval_days', sa.Integer(), nullable=True),
    sa.Column('average_lifespan_years', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('industry_id', sa.UUID(), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('director_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('production_capacity', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('capacity_unit', sa.String(length=50), nullable=True),
    sa.Column('equipment_count', sa.Integer(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('subscription_plan', sa.String(length=50), nullable=True),
    sa.Column('subscription_expires_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('factory_id', sa.UUID(), nullable=False),
    sa.Column('equipment_type_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('inventory_number', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('manufacture_year', sa.Integer(), nullable=True),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('workshop', sa.String(length=100), nullable=True),
    sa.Column('line', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('rated_capacity', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('capacity_unit', sa.String(length=50), nullable=True),
    sa.Column('power_consumption_kw', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('health_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('last_maintenance_date', sa.Date(), nullable=True),
    sa.Column('next_maintenance_date', sa.Date(), nullable=True),
    sa.Column('maintenance_interval_days', sa.Integer(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('health_score >= 0 AND health_score <= 100', name='check_health_score'),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['equipment_types.id'], ),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('factory_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('notification_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('anomalies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('metric_id', sa.UUID(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('anomaly_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('expected_value', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('actual_value', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('deviation_percentage', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('anomaly_type', sa.String(length=100), nullable=True),
    sa.Column('pattern', sa.Text(), nullable=True),
    sa.Column('related_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metrics_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('metric_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=True),
    sa.Column('shift', sa.String(length=50), nullable=True),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('prediction_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('predicted_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prediction_value', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('prediction_label', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('input_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('estimated_cost_if_ignored', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('actual_value', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('actual_occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prediction_accuracy', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expected_benefit', sa.Text(), nullable=True),
    sa.Column('estimated_savings', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('savings_currency', sa.String(length=10), nullable=True),
    sa.Column('payback_period_days', sa.Integer(), nullable=True),
    sa.Column('implementation_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('implementation_time_hours', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('related_anomaly_id', sa.UUID(), nullable=True),
    sa.Column('related_prediction_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['related_anomaly_id'], ['anomalies.id'], ),
    sa.ForeignKeyConstraint(['related_prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendations')
    op.drop_table('predictions')
    op.drop_table('metrics_data')
    op.drop_table('anomalies')
    op.drop_table('users')
    op.drop_table('equipment')
    op.drop_table('factories')
    op.drop_table('equipment_types')
    op.drop_table('metrics_catalog')
    op.drop_table('kpi_calculations')
    op.drop_table('industries')
    # ### end Alembic commands ###

